### PR TITLE
Update to work with dry-types >= 0.15.0

### PR DESCRIPTION
**Pull request by AMHOL**

### CODE REVIEW

**Comment by AMHOL** [comment]
@Kukunin I just realised this repo has 0 watchers, is it no longer maintained?

**Comment by Kukunin** [comment]
@AMHOL Hi Andy. I'm sorry for my abysmal unresponsiveness (14 days ago, huh). 

I merged your pull request. I want to make my packages up-to-date, which I plan to do in the nearest time, but with my current schedule, it might take longer than expected.

I'll try to be at least more responsive, and if someone is willing to help - I can provide write access to the repository.

Thanks for your contribution, I appreciate it

**Comment by AMHOL** [comment]
@Kukunin I'm happy to cut/push a new gem email is andyholland1991@aol.com

**Comment by Kukunin** [comment]
Glad to hear from you. I’ll grant you an access to ruby gems within a day
or two. Currently having unstable schedule.

Thanks

**Comment by Kukunin** [comment]
@AMHOL Hi Andy. Just added you as an owner to https://rubygems.org/gems/rspec-dry-struct. Going to share the writing access to the repository as well

**Comment by AMHOL** [comment]
@Kukunin I pushed `0.5.0`, originally tried to push `0.4.0` as the version constant was set to `0.3.0`, but [0.4.0](https://diff.coditsu.io/gems/rspec-dry-struct/0.3.0/0.4.0) had already been released on July 09, 2019.

**Pull request merged**
